name: test-ec2 login
on:
  push:
    branches:
      - main

jobs:
  ssh-into-EC2:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        name: Checkout
      -
        name: Pull docker image and run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            whoami
            # docker pull angjason/amongus-devtools:latest
            # docker run -d --restart always -p 80:3000 angjason/amongus-devtools:latest
            